orient = 'axial';
exp_setup;
niters = 100;

[x_smpd, ~, nrmsd_smpd, ~, time_smpd] = ADMM_FP_tridiag(y, F, S, CH, CV, beta, xinit, ...
        xinf, niters, 'attempt_par', true, 'pmethod', 'spmd');
[x_pfor, ~, nrmsd_pfor, ~, time_pfor] = ADMM_FP_tridiag(y, F, S, CH, CV, beta, xinit, ...
        xinf, niters, 'attempt_par', true, 'pmethod', 'pfor');
[x_fevl, ~, nrmsd_fevl, ~, time_fevl] = ADMM_FP_tridiag(y, F, S, CH, CV, beta, xinit, ...
        xinf, niters, 'attempt_par', true, 'pmethod', 'feval');
[x, ~, nrmsd, ~, time] = ADMM_FP_tridiag(y, F, S, CH, CV, beta, xinit, ...
        xinf, niters);
[x_warm, ~, nrmsd_warm, ~, time_warm] = ADMM_FP_tridiag(y, F, S, CH, CV, beta, xinit, ...
        xinf, niters, 'warmup', 10);

save(sprintf('%s/%s_PF_timing_%dx%d_%diter_%s.mat', curr_folder, machine(1:3), Nx, Ny, niters, slice_str));
